name: Build and Deploy Hugo Site

on:
  push:
    branches:
      - main  # или замени на ветку, которую используешь

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Install Hugo modules
        run: hugo mod get -u

      - name: Build the website
        run: hugo

      - name: Deploy to external repo
        if: success()
        env:
          TARGET_REPO: ${{ secrets.TARGET_REPO }}  # Add this secret in your repository settings
          TARGET_TOKEN: ${{ secrets.TARGET_TOKEN }}  # Add this secret in your repository settings
          TARGET_BRANCH: gh-pages  # Or any other branch you want to push to
        run: |
          cd public
          git init
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy Hugo site"
          git push --force "https://x-access-token:${{ env.TARGET_TOKEN }}@github.com/${{ env.TARGET_REPO }}.git" master:${{ env.TARGET_BRANCH }}
