name: Build and Deploy Hugo Site

on:
  push:
    branches:
      - main  # укажите ветку, на которую будет триггериться сборка

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: true  # Инициализация сабмодулей

    - name: Set up Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.124.1'  # используйте вашу версию Hugo

    - name: Build site
      run: hugo --gc --minify

    - name: Deploy to Branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        
        # Проверка наличия ветки front
        if git ls-remote --exit-code --heads origin front; then
          echo "Branch 'front' exists."
          git clone --branch front https://${GITHUB_TOKEN}@github.com/${{ github.repository }} front
        else
          echo "Branch 'front' does not exist. Creating it."
          git clone https://${GITHUB_TOKEN}@github.com/${{ github.repository }} front
          cd front
          git checkout --orphan front
          git rm -rf .
          cd ..
        fi

        rsync -av --delete public/ front/
        cd front
        git add .
        git commit -m "Deploy to front branch"
        git push origin front
